# Generated by Django 3.1.12 on 2025-06-21 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ders_programi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blok',
            table='blok',
        ),
        migrations.AlterModelTable(
            name='bolum',
            table='bolum',
        ),
        migrations.AlterModelTable(
            name='ders',
            table='ders',
        ),
        migrations.AlterModelTable(
            name='derslik',
            table='derslik',
        ),
        migrations.AlterModelTable(
            name='dersprogrami',
            table='ders_programi',
        ),
        migrations.AlterModelTable(
            name='kullanici',
            table='kullanici',
        ),
        migrations.AlterModelTable(
            name='ozeldurum',
            table='ozeldurum',
        ),
        migrations.AlterModelTable(
            name='zaman',
            table='zaman',
        ),
    ]
